using ErrorOr;

using Zeus.Api.Domain.Integrations.Discord;
using Zeus.Api.Domain.Integrations.Discord.ValueObjects;
using Zeus.Common.Domain.Authentication.ValueObjects;

namespace Zeus.Api.Application.Interfaces.Services.Integrations.Discord;

public interface IDiscordService
{
    /// <summary>
    /// Get new tokens from Oauth2 code for a discord user
    /// </summary>
    /// <param name="code">The code generated by the discord Oauth2 page</param>
    /// <returns>Tokens of the discord user</returns>
    public Task<ErrorOr<DiscordUserTokens>> GetTokensFromOauth2Async(string code);

    /// <summary>
    /// Get a discord user (/users/@me)
    /// </summary>
    /// <param name="accessToken">The access token of the user (build from Oauth2)</param>
    /// <returns>The discord user</returns>
    public Task<ErrorOr<DiscordUser>> GetUserAsync(AccessToken accessToken);
}
