services:
  zeus-api-web:
    image: zeus-api-web-image
    container_name: zeus-api-web-container
    build:
        context: backend/
        dockerfile: Zeus.Api.Web/Dockerfile
    env_file:
      - .env
    ports:
      - "5090:8080"
