FROM mobile-base

ARG BUILD_MOBILE=false

WORKDIR /app

COPY . .

RUN flutter pub get

RUN if [ "$BUILD_MOBILE" = "true" ]; then flutter build apk --dart-define-from-file=.env; fi

CMD ["sh", "-c", "if [ \"$BUILD_MOBILE\" = \"true\" ]; then flutter build apk --dart-define-from-file=.env && cp build/app/outputs/apk/release/Triggo-release.apk /common/Triggo-release.apk; else echo 'Skipping mobile build'; fi"]