FROM mobile-base

ARG BUILD_MOBILE=false

WORKDIR /app

COPY . .

RUN flutter pub get

RUN flutter build apk --dart-define-from-file=.env

RUN mkdir -p /common

RUN cp build/app/outputs/apk/release/Triggo-release.apk /common/Triggo-release.apk
