name: triggo
description: "Triggo's Android and iOS applications"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.0
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_secure_storage: ^9.2.2
  formz: ^0.8.0
  equatable: ^2.0.7
  flutter_svg: ^2.0.16
  flutter_launcher_icons: ^0.14.1
  json_serializable: ^6.9.0
  provider: ^6.1.2

dev_dependencies:
  mockito: 5.4.4
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  assets:
    - assets/icons/logo.svg
    - assets/icons/bubbles.svg

  uses-material-design: true

  fonts:
    - family: Mada
      fonts:
        - asset: assets/fonts/Mada/Mada-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mada/Mada-ExtraBold.ttf
          weight: 800

    - family: Onest
      fonts:
        - asset: assets/fonts/Onest/Onest-Regular.ttf
        - asset: assets/fonts/Onest/Onest-Medium.ttf
          weight: 500
        - asset: assets/fonts/Onest/Onest-SemiBold.ttf
          weight: 600
