name: triggo
description: "Triggo's Android and iOS applications"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Mada
      fonts:
        - asset: assets/fonts/Mada/Mada-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mada/Mada-ExtraBold.ttf
          weight: 800

    - family: Onest
      fonts:
        - asset: assets/fonts/Onest/Onest-Regular.ttf
        - asset: assets/fonts/Onest/Onest-Medium.ttf
          weight: 500
        - asset: assets/fonts/Onest/Onest-SemiBold.ttf
          weight: 600
