name: triggo
description: "Triggo's Android and iOS applications"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^9.0.0
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_secure_storage: ^9.2.2
  formz: ^0.8.0
  equatable: ^2.0.7
  flutter_svg: ^2.0.16
  flutter_launcher_icons: ^0.14.1
  json_serializable: ^6.9.0
  provider: ^6.1.2
  url_launcher: ^6.3.1
  dotted_border: ^2.1.0
  dotted_line: ^3.2.3
  google_sign_in: ^6.2.2

dev_dependencies:
  mockito: 5.4.4
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  assets:
    - ./assets/icons/academic-cap.svg
    - ./assets/icons/adjustments-horizontal.svg
    - ./assets/icons/adjustments-vertical.svg
    - ./assets/icons/archive-box-arrow-down.svg
    - ./assets/icons/archive-box-x-mark.svg
    - ./assets/icons/archive-box.svg
    - ./assets/icons/arrow-down-circle.svg
    - ./assets/icons/arrow-down-left.svg
    - ./assets/icons/arrow-down-on-square-stack.svg
    - ./assets/icons/arrow-down-on-square.svg
    - ./assets/icons/arrow-down-right.svg
    - ./assets/icons/arrow-down-tray.svg
    - ./assets/icons/arrow-down.svg
    - ./assets/icons/arrow-left-circle.svg
    - ./assets/icons/arrow-left-end-on-rectangle.svg
    - ./assets/icons/arrow-left-start-on-rectangle.svg
    - ./assets/icons/arrow-left.svg
    - ./assets/icons/arrow-long-down.svg
    - ./assets/icons/arrow-long-left.svg
    - ./assets/icons/arrow-long-right.svg
    - ./assets/icons/arrow-long-up.svg
    - ./assets/icons/arrow-path-rounded-square.svg
    - ./assets/icons/arrow-path.svg
    - ./assets/icons/arrow-right-circle.svg
    - ./assets/icons/arrow-right-end-on-rectangle.svg
    - ./assets/icons/arrow-right-start-on-rectangle.svg
    - ./assets/icons/arrow-right.svg
    - ./assets/icons/arrow-top-right-on-square.svg
    - ./assets/icons/arrow-trending-down.svg
    - ./assets/icons/arrow-trending-up.svg
    - ./assets/icons/arrow-up-circle.svg
    - ./assets/icons/arrow-up-left.svg
    - ./assets/icons/arrow-up-on-square-stack.svg
    - ./assets/icons/arrow-up-on-square.svg
    - ./assets/icons/arrow-up-right.svg
    - ./assets/icons/arrow-up-tray.svg
    - ./assets/icons/arrow-up.svg
    - ./assets/icons/arrow-uturn-down.svg
    - ./assets/icons/arrow-uturn-left.svg
    - ./assets/icons/arrow-uturn-right.svg
    - ./assets/icons/arrow-uturn-up.svg
    - ./assets/icons/arrows-pointing-in.svg
    - ./assets/icons/arrows-pointing-out.svg
    - ./assets/icons/arrows-right-left.svg
    - ./assets/icons/arrows-up-down.svg
    - ./assets/icons/at-symbol.svg
    - ./assets/icons/backspace.svg
    - ./assets/icons/backward.svg
    - ./assets/icons/banknotes.svg
    - ./assets/icons/bars-2.svg
    - ./assets/icons/bars-3-bottom-left.svg
    - ./assets/icons/bars-3-bottom-right.svg
    - ./assets/icons/bars-3-center-left.svg
    - ./assets/icons/bars-3.svg
    - ./assets/icons/bars-4.svg
    - ./assets/icons/bars-arrow-down.svg
    - ./assets/icons/bars-arrow-up.svg
    - ./assets/icons/battery-0.svg
    - ./assets/icons/battery-100.svg
    - ./assets/icons/battery-50.svg
    - ./assets/icons/beaker.svg
    - ./assets/icons/bell-alert.svg
    - ./assets/icons/bell-slash.svg
    - ./assets/icons/bell-snooze.svg
    - ./assets/icons/bell.svg
    - ./assets/icons/bolt-slash.svg
    - ./assets/icons/bolt.svg
    - ./assets/icons/book-open.svg
    - ./assets/icons/bookmark-slash.svg
    - ./assets/icons/bookmark-square.svg
    - ./assets/icons/bookmark.svg
    - ./assets/icons/briefcase.svg
    - ./assets/icons/bubbles.svg
    - ./assets/icons/bug-ant.svg
    - ./assets/icons/building-library.svg
    - ./assets/icons/building-office-2.svg
    - ./assets/icons/building-office.svg
    - ./assets/icons/building-storefront.svg
    - ./assets/icons/cake.svg
    - ./assets/icons/calculator.svg
    - ./assets/icons/calendar-days.svg
    - ./assets/icons/calendar.svg
    - ./assets/icons/camera.svg
    - ./assets/icons/chart-bar-square.svg
    - ./assets/icons/chart-bar.svg
    - ./assets/icons/chart-pie.svg
    - ./assets/icons/chat-bubble-bottom-center-text.svg
    - ./assets/icons/chat-bubble-bottom-center.svg
    - ./assets/icons/chat-bubble-left-ellipsis.svg
    - ./assets/icons/chat-bubble-left-right.svg
    - ./assets/icons/chat-bubble-left.svg
    - ./assets/icons/chat-bubble-oval-left-ellipsis.svg
    - ./assets/icons/chat-bubble-oval-left.svg
    - ./assets/icons/chat.svg
    - ./assets/icons/check-badge.svg
    - ./assets/icons/check-circle.svg
    - ./assets/icons/check.svg
    - ./assets/icons/chevron-double-down.svg
    - ./assets/icons/chevron-double-left.svg
    - ./assets/icons/chevron-double-right.svg
    - ./assets/icons/chevron-double-up.svg
    - ./assets/icons/chevron-down.svg
    - ./assets/icons/chevron-left.svg
    - ./assets/icons/chevron-right.svg
    - ./assets/icons/chevron-up-down.svg
    - ./assets/icons/chevron-up.svg
    - ./assets/icons/circle-stack.svg
    - ./assets/icons/clipboard-document-check.svg
    - ./assets/icons/clipboard-document-list.svg
    - ./assets/icons/clipboard-document.svg
    - ./assets/icons/clipboard.svg
    - ./assets/icons/clock.svg
    - ./assets/icons/cloud-arrow-down.svg
    - ./assets/icons/cloud-arrow-up.svg
    - ./assets/icons/cloud.svg
    - ./assets/icons/code-bracket-square.svg
    - ./assets/icons/code-bracket.svg
    - ./assets/icons/cog-6-tooth.svg
    - ./assets/icons/cog-8-tooth.svg
    - ./assets/icons/cog.svg
    - ./assets/icons/command-line.svg
    - ./assets/icons/computer-desktop.svg
    - ./assets/icons/cpu-chip.svg
    - ./assets/icons/credit-card.svg
    - ./assets/icons/cube-transparent.svg
    - ./assets/icons/cube.svg
    - ./assets/icons/currency-bangladeshi.svg
    - ./assets/icons/currency-dollar.svg
    - ./assets/icons/currency-euro.svg
    - ./assets/icons/currency-pound.svg
    - ./assets/icons/currency-rupee.svg
    - ./assets/icons/currency-yen.svg
    - ./assets/icons/cursor-arrow-rays.svg
    - ./assets/icons/cursor-arrow-ripple.svg
    - ./assets/icons/device-phone-mobile.svg
    - ./assets/icons/device-tablet.svg
    - ./assets/icons/discord.svg
    - ./assets/icons/document-arrow-down.svg
    - ./assets/icons/document-arrow-up.svg
    - ./assets/icons/document-chart-bar.svg
    - ./assets/icons/document-check.svg
    - ./assets/icons/document-duplicate.svg
    - ./assets/icons/document-magnifying-glass.svg
    - ./assets/icons/document-minus.svg
    - ./assets/icons/document-plus.svg
    - ./assets/icons/document-text.svg
    - ./assets/icons/document.svg
    - ./assets/icons/ellipsis-horizontal-circle.svg
    - ./assets/icons/ellipsis-horizontal.svg
    - ./assets/icons/ellipsis-vertical.svg
    - ./assets/icons/envelope-open.svg
    - ./assets/icons/envelope.svg
    - ./assets/icons/exclamation-circle.svg
    - ./assets/icons/exclamation-triangle.svg
    - ./assets/icons/eye-dropper.svg
    - ./assets/icons/eye-slash.svg
    - ./assets/icons/eye.svg
    - ./assets/icons/face-frown.svg
    - ./assets/icons/face-smile.svg
    - ./assets/icons/film.svg
    - ./assets/icons/finger-print.svg
    - ./assets/icons/fire.svg
    - ./assets/icons/flag.svg
    - ./assets/icons/folder-arrow-down.svg
    - ./assets/icons/folder-minus.svg
    - ./assets/icons/folder-open.svg
    - ./assets/icons/folder-plus.svg
    - ./assets/icons/folder.svg
    - ./assets/icons/forward.svg
    - ./assets/icons/funnel.svg
    - ./assets/icons/gif.svg
    - ./assets/icons/gift-top.svg
    - ./assets/icons/gift.svg
    - ./assets/icons/globe-alt.svg
    - ./assets/icons/globe-americas.svg
    - ./assets/icons/globe-asia-australia.svg
    - ./assets/icons/globe-europe-africa.svg
    - ./assets/icons/google.svg
    - ./assets/icons/hand-raised.svg
    - ./assets/icons/hand-thumb-down.svg
    - ./assets/icons/hand-thumb-up.svg
    - ./assets/icons/hashtag.svg
    - ./assets/icons/heart.svg
    - ./assets/icons/home-modern.svg
    - ./assets/icons/home.svg
    - ./assets/icons/identification.svg
    - ./assets/icons/inbox-arrow-down.svg
    - ./assets/icons/inbox-stack.svg
    - ./assets/icons/inbox.svg
    - ./assets/icons/information-circle.svg
    - ./assets/icons/key.svg
    - ./assets/icons/language.svg
    - ./assets/icons/lifebuoy.svg
    - ./assets/icons/light-bulb.svg
    - ./assets/icons/link.svg
    - ./assets/icons/list-bullet.svg
    - ./assets/icons/lock-closed.svg
    - ./assets/icons/lock-open.svg
    - ./assets/icons/logo.png
    - ./assets/icons/logo.svg
    - ./assets/icons/magnifying-glass-circle.svg
    - ./assets/icons/magnifying-glass-minus.svg
    - ./assets/icons/magnifying-glass-plus.svg
    - ./assets/icons/magnifying-glass.svg
    - ./assets/icons/map-pin.svg
    - ./assets/icons/map.svg
    - ./assets/icons/megaphone.svg
    - ./assets/icons/microphone.svg
    - ./assets/icons/minus-circle.svg
    - ./assets/icons/minus.svg
    - ./assets/icons/moon.svg
    - ./assets/icons/musical-note.svg
    - ./assets/icons/newspaper.svg
    - ./assets/icons/no-symbol.svg
    - ./assets/icons/notion.svg
    - ./assets/icons/openai.svg
    - ./assets/icons/paint-brush.svg
    - ./assets/icons/paper-airplane.svg
    - ./assets/icons/paper-clip.svg
    - ./assets/icons/pause-circle.svg
    - ./assets/icons/pause.svg
    - ./assets/icons/pencil-square.svg
    - ./assets/icons/pencil.svg
    - ./assets/icons/people.svg
    - ./assets/icons/phone-arrow-down-left.svg
    - ./assets/icons/phone-arrow-up-right.svg
    - ./assets/icons/phone-x-mark.svg
    - ./assets/icons/phone.svg
    - ./assets/icons/photo.svg
    - ./assets/icons/play-circle.svg
    - ./assets/icons/play-pause.svg
    - ./assets/icons/play.svg
    - ./assets/icons/plus-circle.svg
    - ./assets/icons/plus.svg
    - ./assets/icons/power.svg
    - ./assets/icons/presentation-chart-bar.svg
    - ./assets/icons/presentation-chart-line.svg
    - ./assets/icons/printer.svg
    - ./assets/icons/puzzle-piece.svg
    - ./assets/icons/qr-code.svg
    - ./assets/icons/question-mark-circle.svg
    - ./assets/icons/queue-list.svg
    - ./assets/icons/radio.svg
    - ./assets/icons/receipt-percent.svg
    - ./assets/icons/receipt-refund.svg
    - ./assets/icons/rectangle-group.svg
    - ./assets/icons/rectangle-stack.svg
    - ./assets/icons/rocket-launch.svg
    - ./assets/icons/rss.svg
    - ./assets/icons/scale.svg
    - ./assets/icons/scissors.svg
    - ./assets/icons/server-stack.svg
    - ./assets/icons/server.svg
    - ./assets/icons/share.svg
    - ./assets/icons/shield-check.svg
    - ./assets/icons/shield-exclamation.svg
    - ./assets/icons/shopping-bag.svg
    - ./assets/icons/shopping-cart.svg
    - ./assets/icons/signal-slash.svg
    - ./assets/icons/signal.svg
    - ./assets/icons/sparkles.svg
    - ./assets/icons/speaker-wave.svg
    - ./assets/icons/speaker-x-mark.svg
    - ./assets/icons/square-2-stack.svg
    - ./assets/icons/square-3-stack-3d.svg
    - ./assets/icons/squares-2x2.svg
    - ./assets/icons/squares-plus.svg
    - ./assets/icons/star.svg
    - ./assets/icons/stop-circle.svg
    - ./assets/icons/stop.svg
    - ./assets/icons/sun.svg
    - ./assets/icons/swatch.svg
    - ./assets/icons/table-cells.svg
    - ./assets/icons/tag.svg
    - ./assets/icons/ticket.svg
    - ./assets/icons/trash.svg
    - ./assets/icons/trophy.svg
    - ./assets/icons/truck.svg
    - ./assets/icons/tv.svg
    - ./assets/icons/user-circle.svg
    - ./assets/icons/user-group.svg
    - ./assets/icons/user-minus.svg
    - ./assets/icons/user-plus.svg
    - ./assets/icons/user.svg
    - ./assets/icons/users.svg
    - ./assets/icons/variable.svg
    - ./assets/icons/video-camera.svg
    - ./assets/icons/view-columns.svg
    - ./assets/icons/viewfinder-circle.svg
    - ./assets/icons/wallet.svg
    - ./assets/icons/wifi.svg
    - ./assets/icons/window.svg
    - ./assets/icons/wrench-screwdriver.svg
    - ./assets/icons/wrench.svg
    - ./assets/icons/x-circle.svg
    - ./assets/icons/x-mark.svg
    - ./assets/icons/league_of_legends.svg
    - ./assets/icons/github.svg
    - ./assets/icons/gmail.svg

  uses-material-design: true

  fonts:
    - family: Mada
      fonts:
        - asset: assets/fonts/Mada/Mada-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mada/Mada-ExtraBold.ttf
          weight: 800

    - family: Onest
      fonts:
        - asset: assets/fonts/Onest/Onest-Regular.ttf
        - asset: assets/fonts/Onest/Onest-Medium.ttf
          weight: 500
        - asset: assets/fonts/Onest/Onest-SemiBold.ttf
          weight: 600
