using ErrorOr;

using Zeus.Api.Domain.Integrations.Gmail;
using Zeus.Api.Domain.Integrations.Gmail.ValueObjects;
using Zeus.Common.Domain.Authentication.Common;

namespace Zeus.Api.Application.Interfaces.Services.Integrations;

public interface IGmailService
{
    /// <summary>
    /// Get new tokens from Oauth2 code for a Gmail user
    /// </summary>
    /// <param name="code">The code generated by the Gmail Oauth2 page</param>
    /// <returns>Tokens of the Gmail user</returns>
    public Task<ErrorOr<GmailUserTokens>> GetTokensFromOauth2Async(string code);
    
    /// <summary>
    /// Get a Google user
    /// </summary>
    /// <param name="accessToken">The access token of the user (build from Oauth2)</param>
    /// <returns>The Gmail user</returns>
    public Task<ErrorOr<GmailUser>> GetUserAsync(AccessToken accessToken);
}
