using ErrorOr;

using Zeus.Api.Domain.OAuth2.Google;
using Zeus.Api.Domain.OAuth2.Google.ValueObjects;
using Zeus.Common.Domain.Authentication.Common;

namespace Zeus.Api.Application.Interfaces.Services.OAuth2;

public interface IGoogleOAuth2Service
{
    /// <summary>
    /// Get user tokens from OAuth2 code
    /// </summary>
    /// <param name="code">The code generated by the Google sso page</param>
    /// <returns>User tokens</returns>
    public Task<ErrorOr<GoogleUserTokens>> GetTokensFromOauth2Async(string code);

    /// <summary>
    /// Get user for access token
    /// </summary>
    /// <param name="accessToken">The user access token provided by OAuth2</param>
    /// <returns>A google user</returns>
    public Task<ErrorOr<GoogleUser>> GetUserAsync(AccessToken accessToken);
}
