using ErrorOr;

using Zeus.Api.Domain.OAuth2.Google.ValueObjects;

namespace Zeus.Api.Application.Interfaces.Services.OAuth2;

public interface IGoogleOAuth2Service
{
    /// <summary>
    /// Get user tokens from OAuth2 code
    /// </summary>
    /// <param name="code">The code generated by the Google sso page</param>
    /// <returns>User tokens</returns>
    public Task<ErrorOr<GoogleUserTokens>> GetTokensFromOauth2Async(string code);
}
