import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  projectSidebar: [{type: 'autogenerated', dirName: 'project'}],
  docsSidebar: [{type: 'autogenerated', dirName: 'dev'}],
};

export default sidebars;
